FROM quay.io/souravkl11/rgnk-v3:latest

RUN git clone https://github.com/Kermhack5/Kerm-MD
WORKDIR /railway/Raganork
ENV TZ=Africa/Cameroon
RUN yarn install --network-concurrency 1
CMD ["node", "index.js"]
